#!/bin/sh

set -e

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case \\$1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

. /usr/share/initramfs-tools/hook-functions

mv /lib/firmware/updates/qcom/x1e80100/hp/omnibook-x14/qcadsp8380.mbn.disabled /lib/firmware/updates/qcom/x1e80100/hp/omnibook-x14/qcadsp8380.mbn

# Define a list of firmware files to be included

FIRMWARE_FILES="\
updates/qcom/x1e80100/hp/omnibook-x14/qcadsp8380.mbn \
updates/qcom/x1e80100/hp/omnibook-x14/adsp_dtbs.elf \
updates/qcom/x1e80100/hp/omnibook-x14/adspr.jsn \
updates/qcom/x1e80100/hp/omnibook-x14/adsps.jsn \
updates/qcom/x1e80100/hp/omnibook-x14/adspua.jsn \
updates/qcom/x1e80100/hp/omnibook-x14/battmgr.jsn \
updates/qcom/x1e80100/hp/omnibook-x14/qccdsp8380.mbn \
updates/qcom/x1e80100/hp/omnibook-x14/cdsp_dtbs.elf \
updates/qcom/x1e80100/hp/omnibook-x14/cdspr.jsn \
updates/qcom/x1e80100/hp/omnibook-x14/qcdxkmsuc8380.mbn \
updates/qcom/gen70500_gmu.bin.zst \
updates/qcom/gen70500_sqe.fw.zst"

# Copy each firmware file to initramfs
for file in $FIRMWARE_FILES; do
    dir=$(dirname "$file")
    mkdir -p "${DESTDIR}/lib/firmware/${dir}"
    cp "/lib/firmware/${file}" "${DESTDIR}/lib/firmware/${dir}/"
done

mv /lib/firmware/updates/qcom/x1e80100/hp/omnibook-x14/qcadsp8380.mbn /lib/firmware/updates/qcom/x1e80100/hp/omnibook-x14/qcadsp8380.mbn.disabled

